calabash test/data/test.xml test/xproc/basic/compare/compare1.xml > result/compare1.xml
calabash test/data/test.xml test/xproc/basic/compare/compare1_1.xml > result/compare1_1.xml
calabash test/data/test.xml test/xproc/basic/compare/compare1_2.xml > result/compare1_2.xml
calabash test/data/test.xml test/xproc/basic/compare/compare2.xml > result/compare2.xml
calabash test/data/test.xml test/xproc/basic/compare/compare2_1.xml > result/compare2_1.xml
calabash test/data/test.xml test/xproc/basic/compare/compare3.xml > result/compare3.xml
calabash test/data/test.xml test/xproc/basic/compare/compare3_1.xml > result/compare3_1.xml
calabash test/data/test.xml test/xproc/basic/compare/compare3_1_1.xml > result/compare3_1_1.xml
calabash test/data/test.xml test/xproc/basic/compare/compare4.xml > result/compare4.xml
calabash test/data/test.xml test/xproc/basic/compare/compare4_1.xml > result/compare4_1.xml
calabash test/data/test.xml test/xproc/basic/compare/compare4_1_1.xml > result/compare4_1_1.xml
