calabash test/data/test.xml test/xproc/basic/wrap/wrap1.xml > result/wrap1.xml
calabash test/data/test.xml test/xproc/basic/wrap/wrap1_1.xml > result/wrap1_1.xml
calabash test/data/test.xml test/xproc/basic/wrap/wrap1_2.xml > result/wrap1_2.xml
calabash test/data/test.xml test/xproc/basic/wrap/wrap1_3.xml > result/wrap1_3.xml
calabash test/data/test.xml test/xproc/basic/wrap/wrap1_4.xml > result/wrap1_4.xml
calabash test/data/test.xml test/xproc/basic/wrap/wrap2.xml > result/wrap2.xml
calabash test/data/test.xml test/xproc/basic/wrap/wrap2_1.xml > result/wrap2_1.xml
calabash test/data/test.xml test/xproc/basic/wrap/wrap3.xml > result/wrap3.xml
calabash test/data/test.xml test/xproc/basic/wrap/wrap3_1.xml > result/wrap3_1.xml
calabash test/data/test.xml test/xproc/basic/unwrap/unwrap1.xml > result/unwrap1.xml
calabash test/data/test.xml test/xproc/basic/unwrap/unwrap1_1.xml > result/unwrap1_1.xml
